---
- name: adding WAPT nginx vhost from template
  template:
    src: "{{ role_path }}/files/nginx_wapt_template.j2"
    dest: "{{ debian_nginx_conf }}"

- name: "mkdir {{ nginx_ssl_path }}"
  file:
    path: "{{ nginx_ssl_path }}"
    state: directory

- name: mkdir wapt folders
  file:
    path: "{{ item }}"
    state: directory
    owner: wapt
    group: www-data
    mode: 0775
  with_items:
    - "{{ local_repo_path }}/wapt/"
    - "{{ local_repo_path }}/wapt-host/"
    - "{{ local_repo_path }}/waptwua/"

- name: generate dhparam
  openssl_dhparam:
    path: "{{ nginx_ssl_path }}dhparams.pem"
    size: 2048

- name: copy nginx cert
  copy:
    src: "{{ role_path }}/files/cert.pem"
    dest: "{{ nginx_cert }}"

- name: copy nginx key
  copy:
    src: "{{ role_path }}/files/key.pem"
    dest: "{{ nginx_key }}"

- name: enable nginx services
  service: name={{ item }} enabled=yes
  with_items:
    - nginx

- name: start nginx services
  service: name={{ item }} state=restarted
  with_items:
    - nginx
