---
- name: apt-get update
  shell: "apt-get update"
  args:
    warn: false

- name: install dependencies
  apt: name={{item}} state=latest
  with_items:
     - apt-transport-https      
     - dirmngr
     - nginx
     - dialog
     - python-tz
     - cabextract
     - sudo
     - python-psutil
     - krb5-user
     - msktutil
     - python-pyparsing
     - lsb-release
  environment:
    DEBIAN_FRONTEND: noninteractive

